//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruzDDAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTbl()
        {
            this.ItemTbls = new HashSet<ItemTbl>();
            this.VesselTbls = new HashSet<VesselTbl>();
        }

        [Key]
        public int Customer_ID { get; set; }
        [Display(Name = "Customer Name")]
        [Required]
        public string Customer_Name { get; set; }
        [Display(Name = "Customer IC")]
        [Required]
        public string Customer_IC { get; set; }
        [Display(Name = "Date Birth")]
        public Nullable<System.DateTime> Customer_DateBirth { get; set; }
        [Display(Name = "Address")]
        public string Customer_Address { get; set; }
        [Display(Name = "Customer Contact")]
        [Required]
        public string Customer_Contact { get; set; }
        [Display(Name = "Allocated Vessel")]
        public Nullable<int> Customer_Vessel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTbl> ItemTbls { get; set; }
        public virtual VesselTbl VesselTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VesselTbl> VesselTbls { get; set; }
    }
}
