//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruzDDAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SailingVesselTbl
    {
        public int SailingVessel { get; set; }
        public Nullable<int> Schedule_ID { get; set; }
        public Nullable<int> Vessel_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<int> Total_Size { get; set; }
    
        public virtual ScheduleTbl ScheduleTbl { get; set; }
        public virtual VesselTbl VesselTbl { get; set; }
    }
}
