//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruzDDAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ScheduleTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTbl()
        {
            this.SailingVesselTbls = new HashSet<SailingVesselTbl>();
            this.VesselTbls = new HashSet<VesselTbl>();
        }
        [Key]
        public int Schedule_ID { get; set; }
        [Display(Name = "Sailing Begin Route")]
        [Required]
        public string Sailing_Route { get; set; }
        [Display(Name = "Sailing Destination")]
        [Required]
        public string Sailing_Destination { get; set; }
        [Display(Name = "Sailing Departure")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public Nullable<System.DateTime> Sailing_DepartureDate { get; set; }
        [Display(Name = "Sailing Arrival")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public Nullable<System.DateTime> Sailing_ArrivalDate { get; set; }
        [Display(Name = "Available Space")]
        [Required]
        public Nullable<int> Space_Available { get; set; }
        [Display(Name = "Space Size")]
        public Nullable<double> Space_Size { get; set; }
        [Display(Name = "Sail Captain")]
        public string Sailing_Captain { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SailingVesselTbl> SailingVesselTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VesselTbl> VesselTbls { get; set; }
    }
}
