//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruzDDAC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VesselTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VesselTbl()
        {
            this.CustomerTbls = new HashSet<CustomerTbl>();
            this.ItemTbls = new HashSet<ItemTbl>();
            this.SailingVesselTbls = new HashSet<SailingVesselTbl>();
        }

        [Key]
        public int Vessel_ID { get; set; }
        public int Vessel_ScheduleID { get; set; }
        [Display(Name = "Vessel Type")]
        public string Vessel_Type { get; set; }
        [Display(Name = "Vessel Size")]
        public Nullable<int> Vessel_Size { get; set; }
        [Display(Name = "Vessel Name")]
        [Required]
        public string Vessel_Name { get; set; }
        [Display(Name = "Vessel Approval")]
        public string Vessel_Approval { get; set; }
        [Display(Name = "Vessel Customer")]
        public Nullable<int> Vessel_Customer { get; set; }
        [Display(Name = "Vessel Agent")]
        public string Vessel_Agent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTbl> CustomerTbls { get; set; }
        public virtual CustomerTbl CustomerTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTbl> ItemTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SailingVesselTbl> SailingVesselTbls { get; set; }
        public virtual ScheduleTbl ScheduleTbl { get; set; }
    }
}
